apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqldata
  namespace: crud-s3-demo
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: crud-s3-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          args: ["--default-authentication-plugin=mysql_native_password"]
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-cred
                  key: DB_NAME
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-cred
                  key: DB_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-cred
                  key: DB_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              value: changeit
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mysqldata
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: crud-s3-demo
spec:
  selector:
    app: mysql
  ports:
    - name: db
      port: 3306
      targetPort: 3306
